#!/bin/bash

if [ "$#" != "1" ]; then
    echo "usage: delete <remote file/directory to delete>"
    exit 1
fi

if [ "$1" != "" ] && [ "$1" != "/" ] && [ "$1" != "." ]; then 
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    $DIR/mrc.py rm $1
fi