#!/bin/bash

if [ "$#" != "2" ]; then
    echo "Usage: download <from-file> <to-file>"
    exit 1
fi

echo "Downloading $1 -> $2"

mkdir -p $(dirname $2)
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
$DIR/mrc.py download $1 $2
