#!/bin/bash

if [ "$#" != "2" ]; then
    echo "Usage: upload <from-file> <to-file>"
    exit 1
fi

echo "Uploading $1 -> $2"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
$DIR/mrc.py upload $1 $2