#!/bin/bash

if [ "$#" != "1" ]; then
    echo "usage: delete <remote file/directory to delete>"
    exit 1
fi

if [ "$1" != "" ] && [ "$1" != "/" ] && [ "$1" != "." ]; then 
    aws s3 rm $1 --recursive
fi